version: '3.9'

services:
  requester:
    build: .
    image: requester-bot:latest
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - REQBOT_DB_KEY_FILE=/secrets/db_key.txt
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ../.env/secrets:/secrets:ro
